import type { CharacterData } from '../data/characters'

export function makeCharacter(overrides: Partial<CharacterData> = {}): CharacterData {
  return {
    id: 'yanyeeku',
    portrait: '/portraits/yanyeeku.png',
    color: '#a060d0',
    rune: 'Y',
    name: 'Yanyeeku',
    player: 'Player 1',
    race: 'Kitsune',
    subrace: '',
    class: 'Oracle',
    archetype: 'Flame Mystery',
    alignment: 'CG',
    deity: 'Desna',
    level: 1,
    appearance: 'A bright-eyed oracle wrapped in festival colors.',
    hp: { current: 18, max: 30, hitDie: 'd8', baseDieRoll: 8, conBonus: 1 },
    ac: {
      total: 16,
      touch: 12,
      flatFooted: 14,
      components: [
        { source: 'Base', value: 10 },
        { source: 'Armor', value: 4 },
        { source: 'Dex', value: 2 },
      ],
    },
    initiative: '+2',
    speed: '30 ft',
    bab: '+0',
    abilities: [
      { name: 'STR', score: 10, mod: '+0' },
      { name: 'DEX', score: 14, mod: '+2' },
      { name: 'CON', score: 12, mod: '+1' },
      { name: 'INT', score: 11, mod: '+0' },
      { name: 'WIS', score: 13, mod: '+1' },
      { name: 'CHA', score: 18, mod: '+4' },
    ],
    saves: [
      { name: 'Fortitude', ability: 'CON', total: '+1', base: '+0', abilityMod: '+1', magic: '+0', misc: '+0' },
      { name: 'Reflex', ability: 'DEX', total: '+2', base: '+0', abilityMod: '+2', magic: '+0', misc: '+0' },
      { name: 'Will', ability: 'WIS', total: '+3', base: '+2', abilityMod: '+1', magic: '+0', misc: '+0' },
    ],
    skills: [
      { name: 'Diplomacy', ability: 'CHA', total: 8, ranks: 1, abilityMod: 4, misc: 3 },
      { name: 'Perception', ability: 'WIS', total: 7, ranks: 1, abilityMod: 1, misc: 5 },
    ],
    feats: [{ name: 'Selective Channeling', desc: 'Exclude targets from channel energy.' }],
    weapons: [
      {
        display: 'Morningstar +0 (1d8)',
        name: 'Morningstar',
        type: 'Melee',
        atk: '+0',
        dmg: '1d8',
        crit: 'x2',
        range: '-',
        dmgType: 'B/P',
        special: 'Cold iron',
        ammo: '',
      },
    ],
    spells: {
      concentration: '+5',
      list: [
        {
          name: 'Detect Magic',
          level: '0',
          perDay: 'at will',
          castTime: '1 standard action',
          duration: 'concentration',
          range: '60 ft',
          components: 'V, S',
          school: 'divination',
          target: 'cone-shaped emanation',
          cl: 1,
          sr: 'no',
          save: 'none',
          effect: 'Detects magical auras.',
        },
        {
          name: 'Burning Hands',
          level: '1',
          perDay: '1/day',
          castTime: '1 standard action',
          duration: 'instantaneous',
          range: '15 ft',
          components: 'V, S',
          school: 'evocation',
          target: 'cone-shaped burst',
          cl: 1,
          sr: 'yes',
          save: 'Reflex half',
          effect: 'A cone of flame deals fire damage.',
        },
        {
          name: 'Flaming Sphere',
          level: '2',
          perDay: '1/day',
          castTime: '1 standard action',
          duration: '1 round/level',
          range: 'medium',
          components: 'V, S, M',
          school: 'evocation',
          target: '5-ft sphere',
          cl: 1,
          sr: 'yes',
          save: 'Reflex negates',
          effect: 'A rolling ball of fire moves at your command.',
        },
      ],
    },
    inventory: {
      worn: ['Explorer outfit'],
      weapons: ['Morningstar'],
      carried: ['Holy symbol'],
      wealth: { pp: 0, gp: 10, sp: 5, cp: 0 },
    },
    ...overrides,
  }
}
