# FEATURE — Session End & Recap

**ID:** session-end-recap
**Status:** Approved
**Area:** Backend | Frontend
**Tags:** @session @recap @end @llm

---

## Story

> As a **player and GM**,
> I want to end a session and automatically generate a recap and next-session boot context,
> so that continuity is preserved without manual note-taking.

Ending a session triggers two LLM calls: one to write a player-facing recap, one to write a GM-facing boot brief for the next session. Both files are written to `sessions/`, the transcript is saved to `outputs/`, and the session is cleared from memory.

---

## Background

- Given a session has been booted with a valid session_id
- And at least one player turn has been completed

---

## Acceptance Criteria

<!-- ─────────────────────────────────────────────────────────────────────── -->
### AC-001 — Recap and boot files are generated on End Session
<!-- ─────────────────────────────────────────────────────────────────────── -->

**Scenario:** Player clicks End Session after a completed session

```gherkin
Given a session is active with turn history
When  the player clicks "End Session"
Then  the chat shows a status bubble: "Wrapping up the session…"
And   the status updates as each step completes (recap, boot)
And   sessions/session_NNN/recap.md is created with the player-facing recap
And   sessions/session_NNN+1/boot.md is created with the GM-facing context
And   outputs/session_NNN_notes.json is created with the full message transcript
And   after 1.8 seconds the session clears and the UI returns to the splash screen
```

---

<!-- ─────────────────────────────────────────────────────────────────────── -->
### AC-002 — Recap has correct header format
<!-- ─────────────────────────────────────────────────────────────────────── -->

**Scenario:** Generated recap is used as the next session's intro card

```gherkin
Given End Session has been triggered
When  the recap LLM call completes
Then  the recap file starts with "# Session N — Title" (title generated by LLM)
And   the second line is italicised place and date text
And   the narrative body is written in second-person atmospheric prose
And   three --- separators appear at correct positions in the document
```

---

<!-- ─────────────────────────────────────────────────────────────────────── -->
### AC-003 — Boot context has required sections
<!-- ─────────────────────────────────────────────────────────────────────── -->

**Scenario:** Generated boot.md is read into the system prompt at next session start

```gherkin
Given End Session has been triggered
When  the boot generation LLM call completes
Then  boot.md contains: Scene State, What Is Happening Now, Who Is Present, Party Status, What GM Must Not Do
And   the file is written to sessions/session_NNN+1/boot.md
```

---

<!-- ─────────────────────────────────────────────────────────────────────── -->
### AC-004 — Emergency close discards without recap
<!-- ─────────────────────────────────────────────────────────────────────── -->

**Scenario:** Session is closed via DELETE without generating recap

```gherkin
Given a session is active
When  DELETE /api/sessions/{id} is called
Then  outputs/session_NNN_notes.json is saved
And   no recap.md or boot.md is created
And   the session is removed from memory
```

---

## Out of Scope

- Quality of LLM-generated content (prompt engineering, not a spec concern)
- Session intro card display (covered by SPEC-001)

---

## Notes

- See: [INDEX.md §8 — Session End & Recap](INDEX.md)
- Log parsing strips system prompt and `<details>` blocks before feeding to recap LLM
- Emergency close (DELETE) is the "discard" path; End Session (POST /end) is the "save" path
